-- Generated by scripts/generate-seed.mjs. Do not edit by hand.
-- Idempotent: re-running updates rows in place rather than duplicating them.

begin;
set constraints all deferred;

-- ── products ──────────────────────────────────────────────────────────────
insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$cizkejk-njujork$seed$, 570, false,
  true, 6, '{chilled,whole}'::product_format[], $seed$cizkejk-njujork-ab7e1395.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCSe7nWJkmtBKvQsrdagHnkArp7AHp83/1qIJ5BJHzw/UHtVprqXceR19Khysactz//2Q==$seed$, false, 0, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Čizkejk Njujork$seed$, $seed$Gust i kremast, na podlozi od keksa.$seed$
from public.products where slug = $seed$cizkejk-njujork$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Чизкейк Нью-Йорк$seed$, $seed$Плотный и сливочный, на песочной основе.$seed$
from public.products where slug = $seed$cizkejk-njujork$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$New York cheesecake$seed$, $seed$Dense and creamy, on a biscuit base.$seed$
from public.products where slug = $seed$cizkejk-njujork$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$cizkejk-mandarina$seed$, 570, false,
  true, 6, '{chilled,whole}'::product_format[], $seed$cizkejk-mandarina-f1aa80bf.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCR7mRLgb32oRgDPU1P5zei/lWY+7zvLLswBwM8kVoC1jwM7j+NcnLPudT5ex//2Q==$seed$, false, 1, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Čizkejk mandarina$seed$, $seed$Sa svežom mandarinom i listićima nane.$seed$
from public.products where slug = $seed$cizkejk-mandarina$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Чизкейк мандарин$seed$, $seed$Со свежим мандарином и листьями мяты.$seed$
from public.products where slug = $seed$cizkejk-mandarina$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Mandarin cheesecake$seed$, $seed$With fresh mandarin and mint leaves.$seed$
from public.products where slug = $seed$cizkejk-mandarina$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$medovik$seed$, 450, false,
  false, 6, '{chilled,frozen}'::product_format[], $seed$medovik-8e813a15.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBMgdTijfjjceKj29sn86Me5/OuWx2H/9k=$seed$, false, 2, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Medovik$seed$, $seed$Tanki medeni korovi sa kremom od pavlake.$seed$
from public.products where slug = $seed$medovik$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Медовик$seed$, $seed$Тонкие медовые коржи со сметанным кремом.$seed$
from public.products where slug = $seed$medovik$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Medovik honey cake$seed$, $seed$Thin honey layers with sour cream.$seed$
from public.products where slug = $seed$medovik$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$napoleon$seed$, 410, false,
  false, 6, '{chilled,frozen}'::product_format[], $seed$napoleon-2eecf428.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB8U6yH5WHfj0qfGeRUaqoCgAYY+nT6VawKiDb1KkktD//Z$seed$, false, 3, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Napoleon$seed$, $seed$Lisnato testo i vanila krem, klasika.$seed$
from public.products where slug = $seed$napoleon$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Наполеон$seed$, $seed$Слоёное тесто и заварной крем, классика.$seed$
from public.products where slug = $seed$napoleon$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Napoleon$seed$, $seed$Puff pastry and vanilla custard, the classic.$seed$
from public.products where slug = $seed$napoleon$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$medovik-cela-torta$seed$, 5600, false,
  false, 6, '{whole,chilled,frozen}'::product_format[], $seed$medovik-cela-torta-8e813a15.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBMgdTijfjjceKj29sn86Me5/OuWx2H/9k=$seed$, true, 4, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Medovik, cela torta 2,5 kg$seed$, $seed$Ceo medovik, uz prethodni dogovor.$seed$
from public.products where slug = $seed$medovik-cela-torta$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Медовик, целый торт 2,5 кг$seed$, $seed$Целый медовик, по предварительному согласованию.$seed$
from public.products where slug = $seed$medovik-cela-torta$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Medovik, whole cake 2.5 kg$seed$, $seed$The whole medovik, by prior arrangement.$seed$
from public.products where slug = $seed$medovik-cela-torta$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$napoleon-cela-torta-2700$seed$, 7800, false,
  false, 6, '{whole,chilled,frozen}'::product_format[], $seed$napoleon-cela-torta-2700-2eecf428.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB8U6yH5WHfj0qfGeRUaqoCgAYY+nT6VawKiDb1KkktD//Z$seed$, true, 5, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Napoleon, cela torta 2,7 kg$seed$, $seed$Za veće događaje i punu salu.$seed$
from public.products where slug = $seed$napoleon-cela-torta-2700$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Наполеон, целый торт 2,7 кг$seed$, $seed$Для больших событий и полного зала.$seed$
from public.products where slug = $seed$napoleon-cela-torta-2700$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Napoleon, whole cake 2.7 kg$seed$, $seed$For larger events and a full room.$seed$
from public.products where slug = $seed$napoleon-cela-torta-2700$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$napoleon-cela-torta-1300$seed$, 3800, true,
  false, 6, '{whole,chilled,frozen}'::product_format[], $seed$napoleon-cela-torta-1300-2eecf428.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB8U6yH5WHfj0qfGeRUaqoCgAYY+nT6VawKiDb1KkktD//Z$seed$, true, 6, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Napoleon, cela torta 1,3 kg$seed$, $seed$Manja cela torta, za kamerniji sto.$seed$
from public.products where slug = $seed$napoleon-cela-torta-1300$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Наполеон, целый торт 1,3 кг$seed$, $seed$Торт поменьше — для небольшого стола.$seed$
from public.products where slug = $seed$napoleon-cela-torta-1300$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Napoleon, whole cake 1.3 kg$seed$, $seed$A smaller whole cake, for a smaller table.$seed$
from public.products where slug = $seed$napoleon-cela-torta-1300$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$limun-tart$seed$, 460, false,
  false, 6, '{chilled}'::product_format[], $seed$limun-tart-a7c56ae2.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB4RI9pKFxj5iTgCmeVG3zfbYRnnHPFX5LaO6tyzjaSOSvFIulW20cP09ahXKZ//9k=$seed$, false, 7, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Limun tart$seed$, $seed$Prhka korpica, limun krem i beze.$seed$
from public.products where slug = $seed$limun-tart$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Лимонный тарт$seed$, $seed$Песочная корзинка, лимонный курд и меренга.$seed$
from public.products where slug = $seed$limun-tart$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Lemon tart$seed$, $seed$Shortcrust, lemon curd and meringue.$seed$
from public.products where slug = $seed$limun-tart$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$tart-bobice$seed$, 460, false,
  false, 6, '{ambient}'::product_format[], $seed$tart-bobice-881ab9a0.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBWJZQWUBh0O3G4elRC4QDGW/Mf4U0sRGec4k71JI4EjDYnBPaue522P//Z$seed$, true, 8, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Tart sa bobicama$seed$, $seed$Prhka korpica sa kremom i sezonskim bobicama.$seed$
from public.products where slug = $seed$tart-bobice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Ягодный тарт$seed$, $seed$Песочная корзинка с кремом и сезонными ягодами.$seed$
from public.products where slug = $seed$tart-bobice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Berry tart$seed$, $seed$Shortcrust with cream and seasonal berries.$seed$
from public.products where slug = $seed$tart-bobice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$pticje-mleko$seed$, 450, false,
  false, 6, '{chilled}'::product_format[], $seed$pticje-mleko-c0347381.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCoNxPfB9Qf8KODzt/8db/CqwuDhf3ack9jx+tI85VyNi8HHU/41maH/9k=$seed$, true, 9, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Ptičje mleko$seed$, $seed$Vanila sufle u tamnoj čokoladnoj glazuri.$seed$
from public.products where slug = $seed$pticje-mleko$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Птичье молоко$seed$, $seed$Ванильное суфле в тёмной шоколадной глазури.$seed$
from public.products where slug = $seed$pticje-mleko$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Bird's milk soufflé$seed$, $seed$Vanilla soufflé in a dark chocolate glaze.$seed$
from public.products where slug = $seed$pticje-mleko$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$kolutici$seed$, 410, false,
  false, 6, '{chilled}'::product_format[], $seed$kolutici-142c26d8.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBTex2j+TJmV+PMZRgA+1P+32R/5eGH/ATTb6wt0u4iilfO+8AeKcRGhKiCLA45WosW2f/Z$seed$, true, 10, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Kolutići sa kremom$seed$, $seed$Princes testo, krem i malina ili višnja.$seed$
from public.products where slug = $seed$kolutici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Заварные колечки$seed$, $seed$Заварное тесто, крем и малина или вишня.$seed$
from public.products where slug = $seed$kolutici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Choux rings$seed$, $seed$Choux pastry, cream and raspberry or cherry.$seed$
from public.products where slug = $seed$kolutici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$kartoska$seed$, 340, false,
  false, 6, '{chilled,frozen}'::product_format[], $seed$kartoska-7c6aacf4.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBLrVGVylqFZ0bDbu/0p66leFQfso5H901Ss4I7mUtIuDtyccZrdVQFABPSklct2Wh//9k=$seed$, false, 11, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Čokoladna kuglica$seed$, $seed$Od mlevenog keksa, kakaa i putera.$seed$
from public.products where slug = $seed$kartoska$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Картошка$seed$, $seed$Из молотого печенья, какао и масла.$seed$
from public.products where slug = $seed$kartoska$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Chocolate biscuit ball$seed$, $seed$Ground biscuit, cocoa and butter.$seed$
from public.products where slug = $seed$kartoska$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$mravinjak$seed$, 280, false,
  false, 6, '{chilled,frozen}'::product_format[], $seed$mravinjak-4e27168f.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwAvNTZXaK22mRGwd3f6UwarfED/AEdf++TVa1gS5mDOMNtySvGa2ERVRQBwBgUkrluy0P/Z$seed$, true, 12, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Mravinjak$seed$, $seed$Mrvice prhkog testa sa kuvanim kondenzovanim mlekom.$seed$
from public.products where slug = $seed$mravinjak$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Муравейник$seed$, $seed$Песочная крошка с варёной сгущёнкой.$seed$
from public.products where slug = $seed$mravinjak$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Mravinjak$seed$, $seed$Shortcrust crumbs with dulce de leche.$seed$
from public.products where slug = $seed$mravinjak$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$morkovni-keks$seed$, 390, false,
  false, 6, '{ambient,frozen}'::product_format[], $seed$morkovni-keks-8f3f1819.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBPypPLP94Ux3IUGmrKdo+VenpXIdh//9k=$seed$, true, 13, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Kolač od šargarepe$seed$, $seed$Vlažan, sa orasima i začinima.$seed$
from public.products where slug = $seed$morkovni-keks$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Морковный кекс$seed$, $seed$Влажный, с грецким орехом и специями.$seed$
from public.products where slug = $seed$morkovni-keks$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Carrot cake$seed$, $seed$Moist, with walnuts and spices.$seed$
from public.products where slug = $seed$morkovni-keks$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$brauni$seed$, 370, false,
  false, 6, '{ambient}'::product_format[], $seed$brauni-413c2ff4.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCAtnnPLnd16moyy56H8qWHDA5AyB1AqWO2R41Zt2SATzUpFtn/2Q==$seed$, false, 14, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Brauni$seed$, $seed$Gust, na tamnoj čokoladi.$seed$
from public.products where slug = $seed$brauni$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Брауни$seed$, $seed$Плотный, на тёмном шоколаде.$seed$
from public.products where slug = $seed$brauni$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Brownie$seed$, $seed$Dense, on dark chocolate.$seed$
from public.products where slug = $seed$brauni$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$rolnice$seed$, 390, false,
  false, 6, '{ambient}'::product_format[], $seed$rolnice-f3f9278f.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCzFOHyWYDBwFHUmpRKuBknPsKqwwrHOwUnDdRmtDao4wKzUW9Wy5NLRH//2Q==$seed$, false, 15, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Rolnice$seed$, $seed$Hrskave, punjene kuvanim kondenzovanim mlekom.$seed$
from public.products where slug = $seed$rolnice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Трубочки$seed$, $seed$Хрустящие, с варёной сгущёнкой.$seed$
from public.products where slug = $seed$rolnice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Wafer rolls$seed$, $seed$Crisp, filled with dulce de leche.$seed$
from public.products where slug = $seed$rolnice$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$orascici$seed$, 100, false,
  false, 6, '{ambient}'::product_format[], $seed$orascici-f98661e5.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB5kXHJLOOnPv78UuFPr+Yp0yjdGgGE2h9o6ZqIEsMk8nnoK43dHStT/9k=$seed$, false, 16, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Oraščići$seed$, $seed$Punjeni kuvanim kondenzovanim mlekom. Od 40 komada.$seed$
from public.products where slug = $seed$orascici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Орешки$seed$, $seed$С варёной сгущёнкой. От 40 штук.$seed$
from public.products where slug = $seed$orascici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Walnut cookies$seed$, $seed$Filled with dulce de leche. From 40 pieces.$seed$
from public.products where slug = $seed$orascici$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,
  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,
  position, is_published)
values ($seed$sirniki$seed$, 220, true,
  false, 6, '{frozen}'::product_format[], $seed$sirniki-3d7241e4.jpg$seed$,
  $seed$data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wAARCAAMAAoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCkEfaRuBCnBYE4FWEtXZARLFgjP3qom6mMwcvyPyqcXU5GfNasrHRc/9k=$seed$, true, 17, true)
on conflict (slug) do update set
  price_rsd = excluded.price_rsd,
  price_is_placeholder = excluded.price_is_placeholder,
  has_whole = excluded.has_whole,
  whole_multiplier = excluded.whole_multiplier,
  formats = excluded.formats,
  photo_path = excluded.photo_path,
  photo_blur = excluded.photo_blur,
  photo_is_placeholder = excluded.photo_is_placeholder,
  position = excluded.position,
  is_published = excluded.is_published;

insert into public.product_translations (product_id, locale, name, note)
select id, $seed$sr$seed$, $seed$Sirnici, smrznuti$seed$, $seed$Od svežeg sira, peku se na licu mesta.$seed$
from public.products where slug = $seed$sirniki$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$ru$seed$, $seed$Сырники замороженные$seed$, $seed$Из творога, жарятся на месте.$seed$
from public.products where slug = $seed$sirniki$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;
insert into public.product_translations (product_id, locale, name, note)
select id, $seed$en$seed$, $seed$Syrniki, frozen$seed$, $seed$Curd cheese, fried to order.$seed$
from public.products where slug = $seed$sirniki$seed$
on conflict (product_id, locale) do update set
  name = excluded.name, note = excluded.note;

-- ── order form ────────────────────────────────────────────────────────────
insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$venue$seed$, $seed$input$seed$::order_field_control, $seed$text$seed$::order_field_type,
  null, null, $seed$organization$seed$, true, false,
  true, 0)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Objekat$seed$, $seed$Kafić ili restoran$seed$, $seed$$seed$
from public.order_fields where key = $seed$venue$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Заведение$seed$, $seed$Кафе или ресторан$seed$, $seed$$seed$
from public.order_fields where key = $seed$venue$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Venue$seed$, $seed$Café or restaurant$seed$, $seed$$seed$
from public.order_fields where key = $seed$venue$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$contact$seed$, $seed$input$seed$::order_field_control, $seed$text$seed$::order_field_type,
  null, null, $seed$name$seed$, true, false,
  true, 1)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Kontakt osoba$seed$, $seed$Koga da tražimo?$seed$, $seed$$seed$
from public.order_fields where key = $seed$contact$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Контактное лицо$seed$, $seed$Кого спросить?$seed$, $seed$$seed$
from public.order_fields where key = $seed$contact$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Contact person$seed$, $seed$Who should we ask for?$seed$, $seed$$seed$
from public.order_fields where key = $seed$contact$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$phone$seed$, $seed$input$seed$::order_field_control, $seed$tel$seed$::order_field_type,
  null, null, $seed$tel$seed$, true, false,
  true, 2)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Telefon$seed$, $seed$+381 …$seed$, $seed$$seed$
from public.order_fields where key = $seed$phone$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Телефон$seed$, $seed$+381 …$seed$, $seed$$seed$
from public.order_fields where key = $seed$phone$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Phone$seed$, $seed$+381 …$seed$, $seed$$seed$
from public.order_fields where key = $seed$phone$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$email$seed$, $seed$input$seed$::order_field_control, $seed$email$seed$::order_field_type,
  null, null, $seed$email$seed$, false, false,
  true, 3)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Email$seed$, $seed$porudzbine@objekat.rs$seed$, $seed$Samo ako želite račun na mejl.$seed$
from public.order_fields where key = $seed$email$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Email$seed$, $seed$orders@venue.rs$seed$, $seed$Только если нужен счёт на почту.$seed$
from public.order_fields where key = $seed$email$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Email$seed$, $seed$orders@venue.rs$seed$, $seed$Only if you want the invoice by mail.$seed$
from public.order_fields where key = $seed$email$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$city$seed$, $seed$select$seed$::order_field_control, null::order_field_type,
  $seed$cities$seed$, null, null, true, false,
  true, 4)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Grad$seed$, $seed$Izaberite grad$seed$, $seed$$seed$
from public.order_fields where key = $seed$city$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Город$seed$, $seed$Выберите город$seed$, $seed$$seed$
from public.order_fields where key = $seed$city$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$City$seed$, $seed$Choose a city$seed$, $seed$$seed$
from public.order_fields where key = $seed$city$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$date$seed$, $seed$input$seed$::order_field_control, $seed$date$seed$::order_field_type,
  null, null, null, true, false,
  true, 5)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Datum isporuke$seed$, $seed$$seed$, $seed$Najranije dva dana od danas.$seed$
from public.order_fields where key = $seed$date$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Дата доставки$seed$, $seed$$seed$, $seed$Не раньше чем через два дня.$seed$
from public.order_fields where key = $seed$date$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Delivery date$seed$, $seed$$seed$, $seed$Two days from today at the earliest.$seed$
from public.order_fields where key = $seed$date$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

insert into public.order_fields (key, control, input_type, options_source, rows,
  autocomplete, is_required, is_wide, is_enabled, position)
values ($seed$comment$seed$, $seed$textarea$seed$::order_field_control, null::order_field_type,
  null, 3, null, false, true,
  true, 6)
on conflict (key) do update set
  control = excluded.control,
  input_type = excluded.input_type,
  options_source = excluded.options_source,
  rows = excluded.rows,
  autocomplete = excluded.autocomplete,
  is_required = excluded.is_required,
  is_wide = excluded.is_wide,
  is_enabled = excluded.is_enabled,
  position = excluded.position;

insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$sr$seed$, $seed$Još nešto?$seed$, $seed$Vreme isporuke, pakovanje, napomena za kuhinju.$seed$, $seed$$seed$
from public.order_fields where key = $seed$comment$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$ru$seed$, $seed$Что-нибудь ещё?$seed$, $seed$Время доставки, упаковка, примечание для кухни.$seed$, $seed$$seed$
from public.order_fields where key = $seed$comment$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;
insert into public.order_field_translations (field_id, locale, label, placeholder, help)
select id, $seed$en$seed$, $seed$Anything else?$seed$, $seed$Delivery time, packing, a note for the kitchen.$seed$, $seed$$seed$
from public.order_fields where key = $seed$comment$seed$
on conflict (field_id, locale) do update set
  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;

commit;
