/**
 * notify-order — single-file build for the Supabase dashboard editor.
 *
 * GENERATED by scripts/bundle-notify.mjs from supabase/functions/notify-order/
 * (message.ts, push.ts, deliver.ts, index.ts). Do not edit this file: edit those and run
 * `npm run bundle:notify`.
 */

import { createClient, type SupabaseClient } from "jsr:@supabase/supabase-js@2";

// ── message.ts ──────────────────────────────────────────────────────────────

/**
 * The message, and nothing else.
 *
 * Pure on purpose: no Deno, no fetch, no database. Everything here is a string
 * problem, and string problems are the ones worth testing — see
 * `scripts/check-notify-message.ts`, which runs this file under Node precisely
 * because it has no runtime of its own.
 */

export type OrderStatus = "new" | "processing" | "completed" | "canceled";

export type NotifyOrder = {
  id: string;
  number: number;
  created_at: string;
  locale: string;
  total_rsd: number;
  status: OrderStatus;
  /** Counted by the claim, so a log line can say which attempt this was. */
  notify_attempts: number;
  /** Set once announced — the message a status change edits. */
  telegram_message_id?: number | null;
  telegram_chat_id?: number | null;
  /** What the message currently shows; differs from `status` until an edit lands. */
  telegram_status?: OrderStatus | null;
};

export type NotifyItem = {
  name_snapshot: string;
  variant: "piece" | "whole";
  qty: number;
  unit_price_rsd: number;
};

export type NotifyAnswer = {
  field_key: string;
  label_snapshot: string;
  value: string;
  position: number;
};

export type BuildOptions = {
  timeZone: string;
  /** Telegram's hard limit. A parameter so the tests can push against it. */
  limit?: number;
};

/** Telegram refuses a message over this, and a refused message is a lost order. */
export const TELEGRAM_LIMIT = 4096;

/**
 * Every value that came from outside goes through here. No exceptions, and in
 * particular no "this field is a phone number, it is fine" — a form the owner
 * can add fields to has no fields anyone can vouch for.
 *
 * `&` first: escaping it after the others would go back over their semicolons.
 */
export function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * A phone number as Telegram will let us link it.
 *
 * `tel:` is tappable on a phone, which is the difference between a member of
 * staff calling a venue back and a member of staff copying digits by hand. The
 * href is rebuilt from the digits rather than passed through, so nothing a
 * customer types can end up inside the attribute.
 */
function telLink(value: string): string | null {
  const digits = value.replace(/[^\d+]/g, "");
  const normalised = digits.startsWith("+") ? `+${digits.slice(1).replace(/\+/g, "")}` : digits;
  if (normalised.replace(/\D/g, "").length < 6) return null;
  return `<a href="tel:${escapeHtml(normalised)}">${escapeHtml(value)}</a>`;
}

/** A field that holds a telephone number, by key rather than by guessing at text. */
function isPhone(key: string): boolean {
  return /(^|_)(phone|tel|mobile|telefon|telephone)(_|$)/i.test(key);
}

const MONEY = new Intl.NumberFormat("sr-RS", { maximumFractionDigits: 0 });

function money(amount: number): string {
  return `${MONEY.format(amount)} RSD`;
}

/**
 * The time, where the shop is.
 *
 * Not UTC, and not whatever locale the function's runtime happens to have: the
 * person reading this is standing in Belgrade, and "14:32" has to mean the
 * fourteen-thirty they just lived through.
 */
function when(iso: string, timeZone: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return escapeHtml(iso);

  return new Intl.DateTimeFormat("en-GB", {
    timeZone,
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  })
    .format(date)
    .replace(",", "");
}

const LANGUAGE: Record<string, string> = {
  sr: "srpski",
  ru: "русский",
  en: "English",
};

/**
 * The status line, which is the part of the message that changes.
 *
 * A mark as well as a word: in a chat scrolled at speed, the column of marks down
 * the left edge is what tells you which orders are still open. Never the mark
 * alone — the word is what a screen reader, and a tired person, actually reads.
 */
export const STATUS_LINE: Record<OrderStatus, string> = {
  new: "🆕 <b>Nova</b>",
  processing: "⏳ <b>U obradi</b>",
  completed: "✅ <b>Završena</b>",
  canceled: "❌ <b>Otkazana</b>",
};

export function buildMessage(
  order: NotifyOrder,
  items: NotifyItem[],
  answers: NotifyAnswer[],
  options: BuildOptions,
): string {
  const limit = options.limit ?? TELEGRAM_LIMIT;

  // "Porudžbina", not "Nova porudžbina": the message outlives the order being
  // new, and the headline should not start lying the moment it is edited.
  const head = [
    `<b>Porudžbina #${escapeHtml(order.number)}</b> · ${STATUS_LINE[order.status] ?? escapeHtml(order.status)}`,
    `${escapeHtml(when(order.created_at, options.timeZone))} · ` +
      `${escapeHtml(LANGUAGE[order.locale] ?? order.locale)} (${escapeHtml(order.locale)})`,
  ].join("\n");

  const lines = items.map((item) => {
    const name =
      item.variant === "whole"
        ? `${escapeHtml(item.name_snapshot)} <i>(cela torta)</i>`
        : escapeHtml(item.name_snapshot);
    const total = item.unit_price_rsd * item.qty;
    return `• ${name} — ${escapeHtml(item.qty)} × ${escapeHtml(money(item.unit_price_rsd))} = <b>${escapeHtml(money(total))}</b>`;
  });

  const contact = [...answers]
    .sort((a, b) => a.position - b.position)
    .map((answer) => {
      const label = escapeHtml(answer.label_snapshot || answer.field_key);
      const value = isPhone(answer.field_key)
        ? (telLink(answer.value) ?? escapeHtml(answer.value))
        : escapeHtml(answer.value);
      return `<b>${label}:</b> ${value}`;
    });

  const total = `<b>Ukupno: ${escapeHtml(money(order.total_rsd))}</b>`;

  const assemble = (itemCount: number, answerCount: number): string => {
    const shownItems = lines.slice(0, itemCount);
    const omittedItems = lines.length - itemCount;
    const shownAnswers = contact.slice(0, answerCount);
    const omittedAnswers = contact.length - answerCount;

    const itemBlock = [
      ...shownItems,
      ...(omittedItems > 0
        ? [`<i>… i još ${escapeHtml(omittedItems)} stavki — cela lista je u konzoli.</i>`]
        : []),
    ].join("\n");

    const answerBlock = [
      ...shownAnswers,
      ...(omittedAnswers > 0
        ? [`<i>… i još ${escapeHtml(omittedAnswers)} polja — u konzoli.</i>`]
        : []),
    ].join("\n");

    return [head, itemBlock, total, answerBlock].filter(Boolean).join("\n\n");
  };

  /*
   * Too long is solved by dropping whole lines, never by cutting the string.
   * A message sliced at 4096 characters ends inside a tag or an entity about as
   * often as not, and Telegram refuses the malformed result — which turns "the
   * order was large" into "the order vanished".
   *
   * The items go first: forty of them is a good day, and the phone number is
   * what somebody actually needs. The answers go second. What is left after
   * that is a number, a total and where to look, which always fits.
   */
  let itemCount = lines.length;
  let answerCount = contact.length;
  let message = assemble(itemCount, answerCount);

  while (message.length > limit && itemCount > 0) {
    itemCount -= 1;
    message = assemble(itemCount, answerCount);
  }

  while (message.length > limit && answerCount > 0) {
    answerCount -= 1;
    message = assemble(itemCount, answerCount);
  }

  if (message.length > limit) {
    message = [head, total, "<i>Cela porudžbina je u konzoli.</i>"].join("\n\n");
  }

  return message;
}

/**
 * The push notification for a new order.
 *
 * Plain text: a lock screen renders no HTML, so nothing here is escaped — and
 * nothing here is ever interpreted as markup either. Short, because iOS shows two
 * lines and Android about three: who, how much, how many.
 */
export function buildPushMessage(
  order: NotifyOrder,
  items: NotifyItem[],
  answers: NotifyAnswer[],
): { title: string; body: string; url: string; tag: string } {
  const who =
    answers.find((answer) => answer.field_key === "venue")?.value ??
    answers.find((answer) => answer.field_key === "contact")?.value ??
    [...answers].sort((a, b) => a.position - b.position)[0]?.value ??
    "";

  const pieces = items.reduce((sum, item) => sum + item.qty, 0);

  return {
    title: `Nova porudžbina #${order.number}`,
    body: [who.slice(0, 60), `${pieces} kom.`, money(order.total_rsd)].filter(Boolean).join(" · "),
    url: `/admin/orders/${order.id}`,
    // One notification per order: a second push for the same order replaces the
    // first instead of stacking.
    tag: `order-${order.id}`,
  };
}

// ── push.ts ─────────────────────────────────────────────────────────────────

/**
 * Web Push, by hand, on WebCrypto.
 *
 * A push message is encrypted to one browser (RFC 8291, `aes128gcm`) and the
 * request is signed by us (RFC 8292, VAPID), so the browser vendor's push service
 * can deliver it without being able to read it and without taking our word for
 * who sent it.
 *
 * Written against WebCrypto only — no `node:crypto`, no Deno APIs — which is the
 * whole reason it is written here rather than imported: the same file runs in
 * the Edge Function and under Node in `scripts/check-web-push.ts`, where the
 * output is decrypted again and the signature verified.
 */

const encoder = new TextEncoder();

export type PushTarget = {
  id: string;
  endpoint: string;
  /** The browser's public key, base64url, uncompressed P-256 point. */
  p256dh: string;
  /** The browser's auth secret, base64url, 16 bytes. */
  auth: string;
};

export type VapidKeys = {
  /** base64url, 65 bytes: the uncompressed public point. */
  publicKey: string;
  /** base64url, 32 bytes: the private scalar. */
  privateKey: string;
  /** mailto: or https: — who push services contact if something is wrong. */
  subject: string;
};

export type PushResult = {
  ok: boolean;
  status: number;
  /** 404/410: the browser unsubscribed or the subscription expired. Delete it. */
  gone: boolean;
  error?: string;
};

/** One record, so the payload must leave room for the 16-byte tag and delimiter. */
const RECORD_SIZE = 4096;
export const MAX_PAYLOAD = 3000;

export function base64UrlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function base64UrlDecode(value: string): Uint8Array<ArrayBuffer> {
  const base64 = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64 + "=".repeat((4 - (base64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function concat(...parts: Uint8Array[]): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

/** RFC 5869, extract-and-expand in one call — which is what WebCrypto's HKDF is. */
async function hkdf(
  salt: Uint8Array<ArrayBuffer>,
  ikm: Uint8Array<ArrayBuffer>,
  info: Uint8Array<ArrayBuffer>,
  length: number,
): Promise<Uint8Array<ArrayBuffer>> {
  const key = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info },
    key,
    length * 8,
  );
  return new Uint8Array(bits);
}

/**
 * RFC 8291 §3 — encrypt one payload to one browser.
 *
 * `salt` and `localKeys` are parameters only so the tests can pin them; in use
 * both are fresh for every message, which is what makes two identical
 * notifications unlinkable on the wire.
 */
export async function encryptPayload(
  payload: Uint8Array<ArrayBuffer>,
  target: Pick<PushTarget, "p256dh" | "auth">,
  pinned: { salt?: Uint8Array<ArrayBuffer>; localKeys?: CryptoKeyPair } = {},
): Promise<Uint8Array<ArrayBuffer>> {
  if (payload.length > MAX_PAYLOAD) {
    throw new Error(`push payload is ${payload.length} bytes, the limit here is ${MAX_PAYLOAD}`);
  }

  const uaPublic = base64UrlDecode(target.p256dh);
  const authSecret = base64UrlDecode(target.auth);

  const local =
    pinned.localKeys ??
    ((await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, [
      "deriveBits",
    ])) as CryptoKeyPair);
  const localPublic = new Uint8Array(await crypto.subtle.exportKey("raw", local.publicKey));

  const uaKey = await crypto.subtle.importKey(
    "raw",
    uaPublic,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    [],
  );
  const shared = new Uint8Array(
    await crypto.subtle.deriveBits({ name: "ECDH", public: uaKey }, local.privateKey, 256),
  );

  // key_info = "WebPush: info" || 0x00 || ua_public || as_public
  const ikm = await hkdf(
    authSecret,
    shared,
    concat(encoder.encode("WebPush: info\0"), uaPublic, localPublic),
    32,
  );

  const salt = pinned.salt ?? crypto.getRandomValues(new Uint8Array(16));
  const cek = await hkdf(salt, ikm, encoder.encode("Content-Encoding: aes128gcm\0"), 16);
  const nonce = await hkdf(salt, ikm, encoder.encode("Content-Encoding: nonce\0"), 12);

  // One record, so the padding delimiter is 0x02 ("last record") and no padding.
  const key = await crypto.subtle.importKey("raw", cek, "AES-GCM", false, ["encrypt"]);
  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv: nonce },
      key,
      concat(payload, new Uint8Array([2])),
    ),
  );

  // RFC 8188 header: salt(16) · rs(4, big endian) · idlen(1) · keyid(idlen)
  const header = new Uint8Array(21 + localPublic.length);
  header.set(salt, 0);
  new DataView(header.buffer).setUint32(16, RECORD_SIZE);
  header[20] = localPublic.length;
  header.set(localPublic, 21);

  return concat(header, ciphertext);
}

/**
 * RFC 8292 — the `Authorization` header that proves the request is ours.
 *
 * A JWT for the push service's origin, signed with the private half of the key
 * pair the browser was given the public half of when it subscribed.
 */
export async function vapidAuthorization(
  endpoint: string,
  keys: VapidKeys,
  now: number = Date.now(),
): Promise<string> {
  const json = (value: unknown) => base64UrlEncode(encoder.encode(JSON.stringify(value)));

  const unsigned = `${json({ typ: "JWT", alg: "ES256" })}.${json({
    aud: new URL(endpoint).origin,
    // Twelve hours: well under the twenty-four the spec allows.
    exp: Math.floor(now / 1000) + 12 * 60 * 60,
    sub: keys.subject,
  })}`;

  const publicKey = base64UrlDecode(keys.publicKey);
  const signingKey = await crypto.subtle.importKey(
    "jwk",
    {
      kty: "EC",
      crv: "P-256",
      d: keys.privateKey,
      x: base64UrlEncode(publicKey.slice(1, 33)),
      y: base64UrlEncode(publicKey.slice(33, 65)),
      ext: true,
    },
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"],
  );

  // WebCrypto signs ECDSA as r‖s, 64 bytes — exactly the JWS ES256 encoding,
  // with no DER to unwrap.
  const signature = new Uint8Array(
    await crypto.subtle.sign(
      { name: "ECDSA", hash: "SHA-256" },
      signingKey,
      encoder.encode(unsigned),
    ),
  );

  return `vapid t=${unsigned}.${base64UrlEncode(signature)}, k=${keys.publicKey}`;
}

export async function sendPush(
  target: PushTarget,
  message: unknown,
  keys: VapidKeys,
  fetcher: typeof fetch = fetch,
): Promise<PushResult> {
  try {
    const body = await encryptPayload(encoder.encode(JSON.stringify(message)), target);

    const response = await fetcher(target.endpoint, {
      method: "POST",
      headers: {
        authorization: await vapidAuthorization(target.endpoint, keys),
        "content-encoding": "aes128gcm",
        "content-type": "application/octet-stream",
        // A new order is urgent, and worth delivering to a phone that was off
        // for the afternoon — but not tomorrow.
        ttl: String(6 * 60 * 60),
        urgency: "high",
      },
      body,
    });

    const gone = response.status === 404 || response.status === 410;
    if (response.ok) return { ok: true, status: response.status, gone: false };

    const text = await response.text().catch(() => "");
    return {
      ok: false,
      status: response.status,
      gone,
      error: text.slice(0, 300) || `http ${response.status}`,
    };
  } catch (cause) {
    return {
      ok: false,
      status: 0,
      gone: false,
      error: cause instanceof Error ? cause.message : "push failed",
    };
  }
}

// ── deliver.ts ──────────────────────────────────────────────────────────────

/**
 * What happens to one order, independent of where it is running.
 *
 * Everything this needs arrives as a function: send, edit, claim, load, record,
 * push. That is not ceremony — it is the only way the interesting paths can be
 * exercised at all. A revoked token, a chat id pointing at a group the bot was
 * thrown out of, a flood wait, a group promoted to a supergroup mid-service, a
 * message someone deleted by hand before its status changed: none of those can
 * be produced on demand against the real API, and all of them are exactly the
 * cases where an order goes missing. Here they are fixtures — see
 * `scripts/check-notify-delivery.ts`.
 *
 * Three entry points:
 *   · deliver()     a new order: push to the administrators' devices once, then
 *                   announce it in the staff chat (retried until it lands)
 *   · syncStatus()  the console changed a status: edit that order's message
 *   · the test push lives in index.ts, because it is authorised differently
 */

export type TelegramResult = {
  ok: boolean;
  status: number;
  messageId?: number;
  description?: string;
  /** Seconds Telegram asks us to wait, from `parameters.retry_after`. */
  retryAfter?: number;
  /** The id a group was given when it became a supergroup. */
  migrateTo?: number;
};

export type PushOutcome = { sent: number; failed: number; removed: number };

export type Deps = {
  /** One atomic claim: null means someone else already has it, or it is sent. */
  claim: (id: string) => Promise<NotifyOrder | null>;
  /** The order as it stands, with no claim — for edits. */
  loadOrder: (id: string) => Promise<NotifyOrder | null>;
  load: (id: string) => Promise<{ items: NotifyItem[]; answers: NotifyAnswer[] }>;
  getSetting: <T>(key: string) => Promise<T | null>;
  setChatId: (chatId: number) => Promise<void>;
  send: (chatId: number | string, text: string) => Promise<TelegramResult>;
  edit: (chatId: number | string, messageId: number, text: string) => Promise<TelegramResult>;
  record: (
    id: string,
    messageId: number | null,
    error: string | null,
    shown?: { status: OrderStatus; chatId: number | string },
  ) => Promise<void>;
  /** Exactly once per order: true for the first caller, false for every other. */
  claimPush: (id: string) => Promise<boolean>;
  /** Send to every current administrator's devices. Never throws. */
  push: (message: ReturnType<typeof buildPushMessage>) => Promise<PushOutcome>;
  log: (event: string, fields?: Record<string, unknown>) => void;
  sleep: (ms: number) => Promise<void>;
};

export type Outcome = {
  status: number;
  body: Record<string, unknown>;
  headers?: Record<string, string>;
};

/** Long enough to be worth sitting out; past this it is the sweep's problem. */
const INLINE_WAIT_SECONDS = 5;

export async function deliver(id: string, deps: Deps): Promise<Outcome> {
  const order = await deps.claim(id);

  // The idempotency guard, doing its job. Webhooks fire more than once, and two
  // identical orders in a staff chat is worse than one arriving late. 200:
  // whoever called did nothing wrong and must not be told to try again.
  if (!order) {
    deps.log("already_sent", { order_id: id });
    return { status: 200, body: { skipped: "already_sent" } };
  }

  const [{ items, answers }, chatIdSetting, timeZone] = await Promise.all([
    deps.load(id),
    deps.getSetting<number | string>("telegram_chat_id"),
    deps.getSetting<string>("shop_timezone"),
  ]);

  // Push first, and independently: a phone should buzz even while Telegram is
  // misconfigured, and a Telegram retry must never buzz it again.
  await announceByPush(order, items, answers, deps);

  if (chatIdSetting === null || chatIdSetting === "") {
    deps.log("no_chat_id", { order_id: id });
    await deps.record(id, null, "settings.telegram_chat_id is not set");
    return { status: 500, body: { error: "no chat id" } };
  }

  const text = buildMessage(order, items, answers, {
    timeZone: timeZone ?? "Europe/Belgrade",
  });

  let chatId: number | string = chatIdSetting;
  let result = await deps.send(chatId, text);

  /*
   * A group that is upgraded to a supergroup gets a new id, and Telegram hands
   * it back exactly once — in the error body of the request that just failed.
   * Miss it and every order from then on fails with "chat not found" until
   * somebody notices the silence, so it is written down before anything else
   * and the send repeated. This is the only retry that happens inline.
   */
  if (!result.ok && result.migrateTo !== undefined) {
    const migrated = result.migrateTo;
    deps.log("chat_migrated", { order_id: id, from: String(chatId), to: String(migrated) });
    await deps.setChatId(migrated);
    chatId = migrated;
    result = await deps.send(chatId, text);
  }

  const waited = await sitOutFloodWait(result, id, deps, () => deps.send(chatId, text));
  if ("outcome" in waited) return waited.outcome;
  result = waited.result;

  if (!result.ok || result.messageId === undefined) {
    const description = result.description ?? `http ${result.status}`;
    deps.log("send_failed", {
      order_id: id,
      status: result.status,
      attempt: order.notify_attempts,
      description,
    });
    await deps.record(id, null, description);
    // Non-2xx deliberately: the row is what the sweep reads, but a failure
    // should also be a failure in the function's own logs and metrics.
    return { status: 502, body: { error: description } };
  }

  // The status the message was rendered with, not whatever the row says now —
  // if a colleague changed it in the meantime, the two differ and the sweep
  // sends the edit that closes the gap.
  await deps.record(id, result.messageId, null, { status: order.status, chatId });
  deps.log("sent", {
    order_id: id,
    order_number: order.number,
    message_id: result.messageId,
    attempt: order.notify_attempts,
    items: items.length,
    characters: text.length,
  });

  return { status: 200, body: { ok: true, message_id: result.messageId } };
}

/**
 * A status changed in the console: make the order's message say so.
 *
 * An edit, not a new message. The chat is a list of order cards; each one should
 * be true, and a stream of "order 42 is now completed" replies would bury the
 * next order under news about the last one.
 */
export async function syncStatus(id: string, deps: Deps): Promise<Outcome> {
  const order = await deps.loadOrder(id);

  if (!order) {
    deps.log("status_no_order", { order_id: id });
    return { status: 200, body: { skipped: "no_such_order" } };
  }

  // Not announced yet: the announcement will carry whatever the status is by
  // then, so there is nothing to edit.
  if (!order.telegram_message_id) {
    deps.log("status_not_announced", { order_id: id });
    return { status: 200, body: { skipped: "not_announced" } };
  }

  // A second webhook, or the sweep arriving after the trigger already won.
  if (order.telegram_status === order.status) {
    deps.log("status_in_sync", { order_id: id, status: order.status });
    return { status: 200, body: { skipped: "in_sync" } };
  }

  const messageId = order.telegram_message_id;
  const [{ items, answers }, chatIdSetting, timeZone] = await Promise.all([
    deps.load(id),
    deps.getSetting<number | string>("telegram_chat_id"),
    deps.getSetting<string>("shop_timezone"),
  ]);

  // The chat the message lives in — which is not necessarily the chat new
  // orders go to, if the group has been upgraded since.
  const chatId = order.telegram_chat_id ?? chatIdSetting;
  if (chatId === null || chatId === "") {
    deps.log("status_no_chat_id", { order_id: id });
    return { status: 500, body: { error: "no chat id" } };
  }

  const text = buildMessage(order, items, answers, { timeZone: timeZone ?? "Europe/Belgrade" });
  let result = await deps.edit(chatId, messageId, text);

  const waited = await sitOutFloodWait(result, id, deps, () => deps.edit(chatId, messageId, text));
  if ("outcome" in waited) return waited.outcome;
  result = waited.result;

  const description = (result.description ?? "").toLowerCase();

  // Already says this — Telegram refuses an edit that changes nothing, and that
  // refusal is a success as far as the chat is concerned.
  const unchanged = description.includes("message is not modified");

  // Somebody deleted the message by hand, or it can no longer be edited. There
  // is nothing a retry can fix, so it is recorded as settled rather than left
  // for the sweep to fail at every two minutes for a day.
  const impossible =
    description.includes("message to edit not found") ||
    description.includes("message can't be edited");

  if (result.ok || unchanged || impossible) {
    await deps.record(id, messageId, null, { status: order.status, chatId });
    deps.log(impossible ? "status_edit_impossible" : "status_synced", {
      order_id: id,
      status: order.status,
      ...(impossible ? { description } : {}),
    });
    return { status: 200, body: { ok: true, status: order.status } };
  }

  deps.log("status_edit_failed", { order_id: id, status: result.status, description });
  return { status: 502, body: { error: result.description ?? `http ${result.status}` } };
}

/**
 * A flood wait short enough to sit out is sat out, once; a long one is handed
 * back as a 429 with `Retry-After`, and the sweep comes back for it.
 */
async function sitOutFloodWait(
  result: TelegramResult,
  id: string,
  deps: Deps,
  again: () => Promise<TelegramResult>,
): Promise<{ result: TelegramResult } | { outcome: Outcome }> {
  if (result.ok || result.status !== 429 || result.retryAfter === undefined) return { result };

  if (result.retryAfter <= INLINE_WAIT_SECONDS) {
    deps.log("rate_limited_waiting", { order_id: id, retry_after: result.retryAfter });
    await deps.sleep(result.retryAfter * 1000);
    return { result: await again() };
  }

  deps.log("rate_limited", { order_id: id, retry_after: result.retryAfter });
  await deps.record(id, null, `429, retry after ${result.retryAfter}s`);
  return {
    outcome: {
      status: 429,
      body: { error: "rate limited", retry_after: result.retryAfter },
      headers: { "retry-after": String(result.retryAfter) },
    },
  };
}

/** Best effort, exactly once, and never the reason a Telegram delivery fails. */
async function announceByPush(
  order: NotifyOrder,
  items: NotifyItem[],
  answers: NotifyAnswer[],
  deps: Deps,
): Promise<void> {
  try {
    if (!(await deps.claimPush(order.id))) return;
    const outcome = await deps.push(buildPushMessage(order, items, answers));
    deps.log("push", { order_id: order.id, ...outcome });
  } catch (cause) {
    deps.log("push_failed", {
      order_id: order.id,
      message: cause instanceof Error ? cause.message : "unknown",
    });
  }
}

// ── index.ts ────────────────────────────────────────────────────────────────

// jsr: is what the current Edge Runtime documents. If a deploy ever refuses it,
// "https://esm.sh/@supabase/supabase-js@2" is the same library by the older route.

/**
 * notify-order — an order arrived, or changed; tell the people running the shop.
 *
 * Three callers, two ways of proving who they are:
 *
 *   INSERT / SWEEP   the database, on a new order          x-notify-secret
 *   STATUS           the database, on a status change      x-notify-secret
 *   TEST_PUSH        an administrator's browser, from the  their own session,
 *                    console's Notifications page          checked against `admins`
 *
 * The bot token and the Web Push private key live here and nowhere else. This
 * file is the edges — environment, HTTP, authentication, clients; what happens
 * to an order is `deliver.ts`, which has no runtime of its own and is tested.
 *
 * Deliberately absent: `setWebhook`, callback queries, inline buttons. Status
 * changes arrive from the console, not from the chat.
 */

const TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN") ?? "";
const SECRET = Deno.env.get("NOTIFY_WEBHOOK_SECRET") ?? "";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const VAPID_PRIVATE_KEY = Deno.env.get("VAPID_PRIVATE_KEY") ?? "";
const VAPID_SUBJECT = Deno.env.get("VAPID_SUBJECT") ?? "";

/** One line, one JSON object, no free text — and nothing secret, ever. */
function log(event: string, fields: Record<string, unknown> = {}): void {
  console.log(JSON.stringify({ fn: "notify-order", event, ...fields }));
}

/**
 * The console calls the test push straight from the browser, which means a
 * preflight. Nothing here relies on cookies, so a wildcard origin gives nothing
 * away: the request still needs an administrator's own access token.
 */
const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization, x-client-info, apikey, content-type",
  "access-control-allow-methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200, headers: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });
}

/**
 * Constant-time comparison. This secret is compared against whatever anyone on
 * the internet sends; `===` returns fractionally sooner the earlier it finds a
 * difference, and that is measurable to a patient attacker.
 */
function secretMatches(given: string): boolean {
  if (SECRET.length === 0) return false;
  const encoder = new TextEncoder();
  const a = encoder.encode(given);
  const b = encoder.encode(SECRET);
  if (a.length !== b.length) return false;

  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a[i]! ^ b[i]!;
  return diff === 0;
}

async function telegram(method: string, payload: Record<string, unknown>): Promise<TelegramResult> {
  const response = await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      ...payload,
      parse_mode: "HTML",
      // Nothing in the message is worth unfurling, and a preview card under
      // every order would push the next one off the screen.
      link_preview_options: { is_disabled: true },
    }),
  });

  const body = (await response.json().catch(() => ({}))) as {
    ok?: boolean;
    result?: { message_id?: number } | true;
    description?: string;
    parameters?: { retry_after?: number; migrate_to_chat_id?: number };
  };
  const result = typeof body.result === "object" ? body.result : undefined;

  return {
    ok: Boolean(body.ok),
    status: response.status,
    ...(result?.message_id !== undefined ? { messageId: result.message_id } : {}),
    ...(body.description !== undefined ? { description: body.description } : {}),
    ...(body.parameters?.retry_after !== undefined
      ? { retryAfter: body.parameters.retry_after }
      : {}),
    ...(body.parameters?.migrate_to_chat_id !== undefined
      ? { migrateTo: body.parameters.migrate_to_chat_id }
      : {}),
  };
}

/** Null when push is not set up — which is a supported state, not an error. */
async function vapidKeys(supabase: SupabaseClient): Promise<VapidKeys | null> {
  if (!VAPID_PRIVATE_KEY || !VAPID_SUBJECT) return null;
  const { data } = await supabase
    .from("settings")
    .select("value")
    .eq("key", "vapid_public_key")
    .maybeSingle();
  const publicKey = typeof data?.value === "string" ? data.value : "";
  return publicKey ? { publicKey, privateKey: VAPID_PRIVATE_KEY, subject: VAPID_SUBJECT } : null;
}

type SubscriptionRow = PushTarget & { failures: number };

/**
 * Send one message to a set of devices and keep the table honest about them:
 * a device that has gone away (404/410) is deleted, one that failed is counted,
 * one that worked is reset.
 */
async function pushTo(
  supabase: SupabaseClient,
  targets: SubscriptionRow[],
  message: unknown,
  keys: VapidKeys,
): Promise<PushOutcome & { results: { id: string; ok: boolean; error?: string }[] }> {
  const results = await Promise.all(
    targets.map(async (target) => ({ target, result: await sendPush(target, message, keys) })),
  );

  let sent = 0;
  let failed = 0;
  let removed = 0;

  await Promise.all(
    results.map(async ({ target, result }) => {
      if (result.ok) {
        sent += 1;
        await supabase
          .from("push_subscriptions")
          .update({ last_success_at: new Date().toISOString(), failures: 0, last_error: null })
          .eq("id", target.id);
      } else if (result.gone) {
        removed += 1;
        await supabase.from("push_subscriptions").delete().eq("id", target.id);
      } else {
        failed += 1;
        await supabase
          .from("push_subscriptions")
          .update({ failures: target.failures + 1, last_error: result.error ?? null })
          .eq("id", target.id);
      }
    }),
  );

  return {
    sent,
    failed,
    removed,
    results: results.map(({ target, result }) => ({
      id: target.id,
      ok: result.ok,
      ...(result.error ? { error: result.error } : {}),
    })),
  };
}

const SUBSCRIPTION_COLUMNS = "id, endpoint, p256dh, auth, failures";

function dependencies(supabase: SupabaseClient): Deps {
  return {
    log,
    sleep: (ms) => new Promise<void>((resolve) => setTimeout(resolve, ms)),

    send: (chatId, text) => telegram("sendMessage", { chat_id: chatId, text }),
    edit: (chatId, messageId, text) =>
      telegram("editMessageText", { chat_id: chatId, message_id: messageId, text }),

    claim: async (id) => {
      const { data, error } = await supabase.rpc("claim_order_notification", { p_id: id });
      if (error) throw new Error(`claim failed: ${error.message}`);
      const order = data as NotifyOrder | null;
      return order && order.id ? order : null;
    },

    loadOrder: async (id) => {
      const { data, error } = await supabase
        .from("orders")
        .select(
          "id, number, created_at, locale, total_rsd, status, notify_attempts," +
            " telegram_message_id, telegram_chat_id, telegram_status",
        )
        .eq("id", id)
        .maybeSingle();
      if (error) throw new Error(`load failed: ${error.message}`);
      return (data as NotifyOrder | null) ?? null;
    },

    load: async (id) => {
      const [{ data: items }, { data: answers }] = await Promise.all([
        supabase
          .from("order_items")
          .select("name_snapshot, variant, qty, unit_price_rsd")
          .eq("order_id", id),
        supabase
          .from("order_answers")
          .select("field_key, label_snapshot, value, position")
          .eq("order_id", id)
          .order("position"),
      ]);
      return {
        items: (items ?? []) as NotifyItem[],
        answers: (answers ?? []) as NotifyAnswer[],
      };
    },

    getSetting: async <T>(key: string): Promise<T | null> => {
      const { data } = await supabase.from("settings").select("value").eq("key", key).maybeSingle();
      return (data?.value ?? null) as T | null;
    },

    setChatId: async (chatId) => {
      const { error } = await supabase
        .from("settings")
        .update({ value: chatId })
        .eq("key", "telegram_chat_id");
      if (error) log("chat_migration_not_saved", { message: error.message });
    },

    record: async (id, messageId, message, shown) => {
      const { error } = await supabase.rpc("record_order_notification", {
        p_id: id,
        p_message_id: messageId,
        p_error: message,
        p_status: (shown?.status ?? null) as OrderStatus | null,
        p_chat_id: shown?.chatId === undefined ? null : Number(shown.chatId),
      });
      if (error) log("record_failed", { order_id: id, message: error.message });
    },

    claimPush: async (id) => {
      const { data, error } = await supabase.rpc("claim_order_push", { p_id: id });
      if (error) {
        log("push_claim_failed", { order_id: id, message: error.message });
        return false;
      }
      return data === true;
    },

    push: async (message) => {
      const keys = await vapidKeys(supabase);
      if (!keys) return { sent: 0, failed: 0, removed: 0 };

      // Current administrators only: revoking someone's console access has to
      // stop their phone too, without anyone remembering to unsubscribe it.
      const { data: admins } = await supabase.from("admins").select("user_id");
      const ids = (admins ?? []).map((row: { user_id: string }) => row.user_id);
      if (ids.length === 0) return { sent: 0, failed: 0, removed: 0 };

      const { data: targets } = await supabase
        .from("push_subscriptions")
        .select(SUBSCRIPTION_COLUMNS)
        .in("user_id", ids);

      const { sent, failed, removed } = await pushTo(
        supabase,
        (targets ?? []) as SubscriptionRow[],
        message,
        keys,
      );
      return { sent, failed, removed };
    },
  };
}

/**
 * "Send a test" from the Notifications page.
 *
 * Authorised by the administrator's own session rather than the shared secret —
 * the browser must never hold that — and sent only to their own devices.
 */
async function testPush(request: Request, supabase: SupabaseClient): Promise<Response> {
  const authorization = request.headers.get("authorization") ?? "";
  if (!ANON_KEY || !authorization.startsWith("Bearer ")) {
    return json({ error: "sign in first" }, 401, CORS);
  }

  const asUser = createClient(SUPABASE_URL, ANON_KEY, {
    global: { headers: { authorization } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const {
    data: { user },
  } = await asUser.auth.getUser(authorization.slice("Bearer ".length));
  const { data: allowed } = await asUser.rpc("is_admin");

  if (!user || !allowed) {
    log("test_push_refused", { user: user?.id ?? null });
    return json({ error: "administrators only" }, 403, CORS);
  }

  const keys = await vapidKeys(supabase);
  if (!keys) {
    log("test_push_not_configured", { user: user.id });
    return json({ error: "push is not configured on the server" }, 503, CORS);
  }

  const { data: targets } = await supabase
    .from("push_subscriptions")
    .select(SUBSCRIPTION_COLUMNS)
    .eq("user_id", user.id);

  const outcome = await pushTo(
    supabase,
    (targets ?? []) as SubscriptionRow[],
    {
      title: "basic — test",
      body: "Push notifications reach this device.",
      url: "/admin/notifications",
      tag: "test",
    },
    keys,
  );

  log("test_push", {
    user: user.id,
    sent: outcome.sent,
    failed: outcome.failed,
    removed: outcome.removed,
  });
  return json(outcome, 200, CORS);
}

Deno.serve(async (request: Request): Promise<Response> => {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (request.method !== "POST") return new Response("method not allowed", { status: 405 });

  if (!SUPABASE_URL || !SERVICE_KEY) {
    log("misconfigured", { url: Boolean(SUPABASE_URL), service_key: Boolean(SERVICE_KEY) });
    return new Response("not configured", { status: 500 });
  }

  // Service role: the only thing in this system that reads orders without being
  // a signed-in administrator. RLS is what makes that a deliberate act rather
  // than an oversight, so it lives here and not in the site.
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const payload = (await request.json().catch(() => ({}))) as {
    type?: string;
    record?: { id?: string };
    id?: string;
  };

  if (payload.type === "TEST_PUSH") return testPush(request, supabase);

  if (!secretMatches(request.headers.get("x-notify-secret") ?? "")) {
    log("unauthorised", { from: request.headers.get("x-forwarded-for") ?? "unknown" });
    return new Response("unauthorised", { status: 401 });
  }

  if (!TOKEN) {
    log("misconfigured", { token: false });
    return new Response("not configured", { status: 500 });
  }

  const id = payload.record?.id ?? payload.id;
  if (typeof id !== "string" || id.length === 0) {
    log("no_order_id", { type: payload.type ?? "unknown" });
    return new Response("no order id", { status: 400 });
  }

  try {
    const deps = dependencies(supabase);
    const outcome =
      payload.type === "STATUS" ? await syncStatus(id, deps) : await deliver(id, deps);
    return json(outcome.body, outcome.status, outcome.headers ?? {});
  } catch (cause) {
    // A thrown error means a database call failed, not Telegram — the attempt
    // is already counted, so the sweep will come back for it.
    log("failed", { order_id: id, message: cause instanceof Error ? cause.message : "unknown" });
    return json({ error: "internal" }, 500);
  }
});
