/**
 * One script that puts the database back: supabase/restore/01-restore.sql.
 *
 *   npm run build:restore
 *
 * Clears everything out of `public` — ours and anything a foreign project's
 * migrations put there — then runs every migration in order and the seed, all
 * inside one transaction. If any statement fails, nothing has changed: the
 * database is exactly as it was before the script started, and the error says
 * which statement it was.
 *
 * Generated rather than hand-assembled, so it can never drift from the
 * migrations it claims to contain.
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const migrationsDir = join(root, "supabase/migrations");
const target = join(root, "supabase/restore/01-restore.sql");

const migrations = (await readdir(migrationsDir)).filter((name) => name.endsWith(".sql")).sort();

// The seed brackets itself in its own transaction; inside ours, its BEGIN would
// only warn and its COMMIT would end our transaction halfway through.
const seed = (await readFile(join(root, "supabase/seed.sql"), "utf8"))
  .split("\n")
  .filter((line) => !/^\s*(begin|commit);\s*$/i.test(line))
  .join("\n");

const cleanup = `
-- ── 1. clear public ──────────────────────────────────────────────────────────
--
-- Object by object, not \`drop schema public cascade\`. Dropping the schema would
-- also drop Supabase's grants and default privileges on it — the ones that let
-- anon, authenticated and service_role see anything at all — and they would have
-- to be recreated by hand exactly right. Emptying it keeps them.
--
-- Anything that belongs to an extension is left alone: it is the extension's to
-- remove, and Supabase owns most of them.

do $$
declare
  r record;
begin
  for r in
    select c.oid, c.relkind
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind in ('v', 'm', 'r', 'p', 'f', 'S')
       and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
     order by case c.relkind when 'v' then 0 when 'm' then 1 when 'S' then 3 else 2 end
  loop
    -- A cascade from an earlier drop may already have taken it.
    continue when not exists (select 1 from pg_class where oid = r.oid);
    execute format(
      'drop %s if exists %s cascade',
      case r.relkind
        when 'v' then 'view'
        when 'm' then 'materialized view'
        when 'S' then 'sequence'
        when 'f' then 'foreign table'
        else 'table'
      end,
      r.oid::regclass
    );
  end loop;

  for r in
    select p.oid
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  loop
    continue when not exists (select 1 from pg_proc where oid = r.oid);
    execute format('drop routine if exists %s cascade', r.oid::regprocedure);
  end loop;

  for r in
    select t.oid
      from pg_type t
      join pg_namespace n on n.oid = t.typnamespace
     where n.nspname = 'public'
       and t.typtype in ('e', 'd', 'c', 'r')
       and (t.typrelid = 0 or (select relkind from pg_class where oid = t.typrelid) = 'c')
       and not exists (select 1 from pg_depend d where d.objid = t.oid and d.deptype = 'e')
  loop
    continue when not exists (select 1 from pg_type where oid = r.oid);
    execute format('drop type if exists %s cascade', r.oid::regtype);
  end loop;
end $$;

-- Our two storage policies. The admin one went with public.is_admin(); the read
-- one does not depend on anything in public and would survive, and 0001 would
-- then refuse to create it a second time.
drop policy if exists product_photos_read on storage.objects;
drop policy if exists product_photos_admin on storage.objects;

-- The foreign project's migration history, if it was applied with the CLI. It
-- describes migrations this database no longer contains, and would make any
-- future \`supabase db push\` from either project refuse to run.
do $$
begin
  if to_regclass('supabase_migrations.schema_migrations') is not null then
    delete from supabase_migrations.schema_migrations;
  end if;
end $$;
`;

const parts = [
  `-- GENERATED by scripts/build-restore.mjs — do not edit; run \`npm run build:restore\`.
--
-- Puts the basic database back: clears \`public\`, then every migration in order
-- (${migrations.join(", ")}) and the seed.
--
-- One transaction. If any statement fails, nothing changes — read the error,
-- fix, run again. Safe to run more than once.
--
-- Not touched: auth users, storage files, Vault secrets, cron jobs other than
-- ours, Edge Functions and their secrets. See 00-inventory.sql for what is there.

begin;

-- The deferred "published needs a default-language name" checks run at COMMIT,
-- after the seed has written every translation.
set constraints all deferred;
`,
  cleanup,
  ...(await Promise.all(
    migrations.map(async (name) => {
      const sql = await readFile(join(migrationsDir, name), "utf8");
      return `\n-- ════ ${name} ${"═".repeat(Math.max(0, 66 - name.length))}\n\n${sql.trim()}\n`;
    }),
  )),
  `\n-- ════ seed.sql ${"═".repeat(58)}\n\n${seed.trim()}\n`,
  `
-- ── done ─────────────────────────────────────────────────────────────────────
commit;

select
  (select count(*) from public.products where is_published) as published_products,
  (select count(*) from public.order_fields where is_enabled) as order_fields,
  (select count(*) from public.settings) as settings_rows;
`,
];

await mkdir(dirname(target), { recursive: true });
await writeFile(target, parts.join("\n"));
console.log(`written supabase/restore/01-restore.sql — ${migrations.length} migrations + seed`);
