/**
 * Writes supabase/seed.sql from the fixtures the site already ships.
 *
 * The seed is generated rather than hand-written so it cannot drift from
 * `src/lib/catalog/products.ts`, `photos.json` and the dictionaries. When the
 * console can edit products, the fixtures go and this script goes with them.
 *
 *   node --experimental-strip-types scripts/generate-seed.mjs
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const { PRODUCTS, WHOLE_MULTIPLIER } = await import(join(root, "src/lib/catalog/products.ts"));
const { ORDER_FIELDS } = await import(join(root, "src/lib/order/fields.ts"));
/* Read rather than imported: `photos.json` is the one thing here that is not a
   module, and Node's JSON import attribute is not worth writing into the app. */
const PHOTOS = JSON.parse(await readFile(join(root, "src/lib/catalog/photos.json"), "utf8"));
const { en } = await import(join(root, "src/lib/i18n/messages/en.ts"));
const { sr } = await import(join(root, "src/lib/i18n/messages/sr.ts"));
const { ru } = await import(join(root, "src/lib/i18n/messages/ru.ts"));

const DICTS = { sr, ru, en };
const LOCALES = ["sr", "ru", "en"];

/** Dollar-quoting: a name with an apostrophe must not be able to end a literal. */
const q = (value) => (value === null || value === undefined ? "null" : `$seed$${value}$seed$`);
const bool = (value) => (value ? "true" : "false");

const lines = [
  "-- Generated by scripts/generate-seed.mjs. Do not edit by hand.",
  "-- Idempotent: re-running updates rows in place rather than duplicating them.",
  "",
  "begin;",
  "set constraints all deferred;",
  "",
];

lines.push("-- ── products ──────────────────────────────────────────────────────────────");
PRODUCTS.forEach((product, index) => {
  const photo = PHOTOS[product.slug] ?? {};
  const formats = `'{${product.formats.join(",")}}'::product_format[]`;

  lines.push(
    `insert into public.products (slug, price_rsd, price_is_placeholder, has_whole,`,
    `  whole_multiplier, formats, photo_path, photo_blur, photo_is_placeholder,`,
    `  position, is_published)`,
    `values (${q(product.slug)}, ${product.price}, ${bool(product.priceIsPlaceholder)},`,
    `  ${bool(product.whole)}, ${WHOLE_MULTIPLIER}, ${formats}, ${q(photo.file ?? null)},`,
    `  ${q(photo.blur ?? null)}, ${bool(product.photoIsPlaceholder)}, ${index}, true)`,
    `on conflict (slug) do update set`,
    `  price_rsd = excluded.price_rsd,`,
    `  price_is_placeholder = excluded.price_is_placeholder,`,
    `  has_whole = excluded.has_whole,`,
    `  whole_multiplier = excluded.whole_multiplier,`,
    `  formats = excluded.formats,`,
    `  photo_path = excluded.photo_path,`,
    `  photo_blur = excluded.photo_blur,`,
    `  photo_is_placeholder = excluded.photo_is_placeholder,`,
    `  position = excluded.position,`,
    `  is_published = excluded.is_published;`,
    "",
  );

  for (const locale of LOCALES) {
    lines.push(
      `insert into public.product_translations (product_id, locale, name, note)`,
      `select id, ${q(locale)}, ${q(product.name[locale])}, ${q(product.note[locale])}`,
      `from public.products where slug = ${q(product.slug)}`,
      `on conflict (product_id, locale) do update set`,
      `  name = excluded.name, note = excluded.note;`,
    );
  }
  lines.push("");
});

lines.push("-- ── order form ────────────────────────────────────────────────────────────");
ORDER_FIELDS.forEach((field, index) => {
  const control = field.control;
  const inputType = control === "input" ? q(field.type) : "null";
  const optionsSource = control === "select" ? q(field.options) : "null";
  const rows = control === "textarea" ? String(field.rows) : "null";
  const autocomplete = control === "input" && field.autoComplete ? q(field.autoComplete) : "null";

  lines.push(
    `insert into public.order_fields (key, control, input_type, options_source, rows,`,
    `  autocomplete, is_required, is_wide, is_enabled, position)`,
    `values (${q(field.key)}, ${q(control)}::order_field_control, ${inputType}::order_field_type,`,
    `  ${optionsSource}, ${rows}, ${autocomplete}, ${bool(field.required)}, ${bool(field.wide)},`,
    `  true, ${index})`,
    `on conflict (key) do update set`,
    `  control = excluded.control,`,
    `  input_type = excluded.input_type,`,
    `  options_source = excluded.options_source,`,
    `  rows = excluded.rows,`,
    `  autocomplete = excluded.autocomplete,`,
    `  is_required = excluded.is_required,`,
    `  is_wide = excluded.is_wide,`,
    `  is_enabled = excluded.is_enabled,`,
    `  position = excluded.position;`,
    "",
  );

  for (const locale of LOCALES) {
    const text = DICTS[locale].order.fields[field.key];
    lines.push(
      `insert into public.order_field_translations (field_id, locale, label, placeholder, help)`,
      `select id, ${q(locale)}, ${q(text.label)}, ${q(text.placeholder ?? "")}, ${q(text.help ?? "")}`,
      `from public.order_fields where key = ${q(field.key)}`,
      `on conflict (field_id, locale) do update set`,
      `  label = excluded.label, placeholder = excluded.placeholder, help = excluded.help;`,
    );
  }
  lines.push("");
});

lines.push("commit;", "");

await writeFile(join(root, "supabase/seed.sql"), lines.join("\n"), "utf8");
console.log(`seed written — ${PRODUCTS.length} products, ${ORDER_FIELDS.length} form fields`);
